import { useState } from 'react';

export default function CycleModal({ cycleCount, nodeCount, cycles, onClose }) {
  const [copied, setCopied] = useState(false);

  if (cycleCount === null) return null;

  const hasCycles = cycleCount > 0;

  // Generate detailed report for coding agent
  const generateReport = () => {
    if (!hasCycles) {
      return `# Circular Dependency Analysis Report

## Summary
✅ **No circular dependencies detected**

Your codebase has a clean, acyclic dependency graph. All imports form a directed acyclic graph (DAG).

## Benefits
- Clear initialization order
- Easier to understand dependencies
- Better tree-shaking and bundling
- Simpler testing and mocking

## Recommendation
Continue maintaining this clean architecture. Avoid introducing circular imports in future changes.
`;
    }

    let report = `# Circular Dependency Analysis Report

## Summary
🔴 **${cycleCount} circular ${cycleCount === 1 ? 'dependency' : 'dependencies'} detected**
📊 **${nodeCount} ${nodeCount === 1 ? 'file' : 'files'} involved**

## What are Circular Dependencies?
Files that import each other in a loop (A → B → C → A). This can cause:
- Initialization order issues
- Runtime errors or undefined values
- Harder to understand and maintain code
- Bundler warnings or failures

## Detected Cycles

`;

    if (cycles && cycles.length > 0) {
      cycles.forEach((cycle, idx) => {
        report += `### Cycle ${idx + 1} (${cycle.length} files)\n\n`;
        report += '```\n';
        cycle.forEach((file, i) => {
          report += `${file}\n`;
          if (i < cycle.length - 1) {
            report += '  ↓ imports\n';
          } else {
            report += '  ↓ imports (back to start)\n';
          }
        });
        report += `${cycle[0]}\n`;
        report += '```\n\n';
      });
    }

    report += `## Recommendations

1. **Extract Shared Code**: Move common functionality to a separate module that both files can import
2. **Dependency Inversion**: Use interfaces or abstract classes to break the cycle
3. **Merge Files**: If the files are tightly coupled, consider merging them into one module
4. **Lazy Loading**: Use dynamic imports to break the circular dependency at runtime

## Next Steps

1. Review each cycle listed above
2. Identify the root cause of the circular dependency
3. Refactor the code to break the cycle using one of the recommendations
4. Re-run cycle detection to verify the fix

---
Generated by IntelliMap - Code Architecture Visualizer
`;

    return report;
  };

  const handleCopy = async () => {
    const report = generateReport();
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50">
      <div className="bg-navy border-2 border-slate rounded-lg shadow-2xl max-w-md w-full mx-4">
        {/* Header */}
        <div className={`px-6 py-4 border-b ${hasCycles ? 'border-rust bg-rust/20' : 'border-sage bg-sage/20'}`}>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="text-3xl">
                {hasCycles ? '🔴' : '✅'}
              </div>
              <div>
                <h2 className="text-xl font-bold text-cream">
                  {hasCycles ? 'Circular Dependencies Found' : 'No Cycles Detected'}
                </h2>
                <p className="text-sm text-mint mt-1">
                  {hasCycles
                    ? 'Your codebase has circular import dependencies'
                    : 'Your dependency graph is acyclic'}
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="text-mint hover:text-cream text-2xl leading-none"
              title="Close"
            >
              ×
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="px-6 py-5">
          {hasCycles ? (
            <div className="space-y-4">
              {/* Stats */}
              <div className="bg-slate rounded-lg p-4 border border-teal/30">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <div className="text-2xl font-bold text-rust">{cycleCount}</div>
                    <div className="text-xs text-mint uppercase tracking-wide">
                      {cycleCount === 1 ? 'Cycle' : 'Cycles'}
                    </div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-rust">{nodeCount}</div>
                    <div className="text-xs text-mint uppercase tracking-wide">
                      {nodeCount === 1 ? 'File' : 'Files'} Involved
                    </div>
                  </div>
                </div>
              </div>

              {/* Explanation */}
              <div className="text-sm text-mint space-y-2">
                <p>
                  <strong className="text-cream">What are circular dependencies?</strong>
                </p>
                <p className="text-teal">
                  Files that import each other in a loop (A → B → C → A). This can cause:
                </p>
                <ul className="list-disc list-inside text-teal space-y-1 ml-2">
                  <li>Initialization order issues</li>
                  <li>Runtime errors or undefined values</li>
                  <li>Harder to understand and maintain code</li>
                  <li>Bundler warnings or failures</li>
                </ul>
              </div>

              {/* Cycle Details */}
              {cycles && cycles.length > 0 && (
                <div className="bg-slate border border-teal/30 rounded-lg p-3 max-h-48 overflow-y-auto">
                  <div className="text-xs text-cream font-semibold mb-2">📋 Detected Cycles:</div>
                  <div className="space-y-3">
                    {cycles.map((cycle, idx) => (
                      <div key={idx} className="text-xs">
                        <div className="text-mint font-semibold mb-1">
                          Cycle {idx + 1} ({cycle.length} files):
                        </div>
                        <div className="font-mono text-cream bg-navy rounded p-2 space-y-0.5">
                          {cycle.map((file, i) => (
                            <div key={i}>
                              <div className="text-peach">{file}</div>
                              {i < cycle.length - 1 && (
                                <div className="text-teal ml-2">↓ imports</div>
                              )}
                            </div>
                          ))}
                          <div className="text-teal ml-2">↓ imports (back to start)</div>
                          <div className="text-peach">{cycle[0]}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Actions */}
              <div className="bg-teal/20 border border-teal rounded-lg p-3">
                <div className="text-xs text-cream">
                  <strong>💡 Next Steps:</strong>
                  <ul className="mt-2 space-y-1 ml-4 list-disc">
                    <li>Cycles are highlighted in <span className="text-rust font-semibold">red</span> on the graph</li>
                    <li>Press <kbd className="px-1.5 py-0.5 bg-slate border border-teal/30 rounded text-xs font-mono">f</kbd> to re-focus on cycles</li>
                    <li>Copy the report below and share with your coding agent</li>
                  </ul>
                </div>
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              {/* Success message */}
              <div className="bg-sage/20 border border-sage rounded-lg p-4">
                <p className="text-cream text-sm">
                  🎉 <strong>Great news!</strong> Your codebase has no circular dependencies.
                  This means your imports form a clean, directed acyclic graph (DAG).
                </p>
              </div>

              {/* Benefits */}
              <div className="text-sm text-mint space-y-2">
                <p>
                  <strong className="text-cream">Benefits of an acyclic graph:</strong>
                </p>
                <ul className="list-disc list-inside text-teal space-y-1 ml-2">
                  <li>Clear initialization order</li>
                  <li>Easier to understand dependencies</li>
                  <li>Better tree-shaking and bundling</li>
                  <li>Simpler testing and mocking</li>
                </ul>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate border-t border-teal/30 rounded-b-lg flex justify-between items-center">
          <button
            onClick={handleCopy}
            className="px-4 py-2 bg-navy hover:bg-teal/20 text-cream border border-teal/30 hover:border-teal rounded font-semibold transition flex items-center gap-2"
            title="Copy detailed report to clipboard"
          >
            {copied ? (
              <>
                <span>✓</span>
                <span>Copied!</span>
              </>
            ) : (
              <>
                <span>📋</span>
                <span>Copy Report</span>
              </>
            )}
          </button>
          <button
            onClick={onClose}
            className={`px-4 py-2 rounded font-semibold transition ${
              hasCycles
                ? 'bg-rust hover:bg-orange text-white border border-rust'
                : 'bg-sage hover:bg-olive text-white border border-sage'
            }`}
          >
            {hasCycles ? 'View Cycles' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
}

